### ISSUE TITLE
[Question] can nv-file-drop div open the input file window on click?

### ISSUE THREAD

**Issue by cosme-benito** [nervgh/angular-file-upload#417] opened 2015-05-18 10:32 UTC
Sorry if this was already asked or answered anywhere, I couldn't find it.

I'm currently using the nv-file-drop and it works very well. However some users prefer to select the files using the OS explorer, and that's fine. I was wondering if it was possible to click the nv-fole-drop DIV and open the OS modal, much like an input file. 

Thanks in advance.

**Comment by aderowbotham** [comment] 2015-05-21 21:03
+1 for this question. I have tried adding `ng-file-select` to the drop area but that doesn't work.

Presumable something could be triggered with `ng-click=""` but, reading the source code, it's not obvious what. In a jQuery-based application I'd probably trigger a click event on a hidden `<input type="file">` element.

**Comment by faxdata** [comment] 2015-05-25 21:56
+1 and hi @cosme-benito @aderowbotham !

Found any smooth solution to this? I would like my drop zone div to be clickable on a mobile device.

**Comment by aderowbotham** [comment] 2015-05-26 08:22
@faxdata No. I gave up trying and have switched to using alternative module [ng-file-upload](https://github.com/danialfarid/ng-file-upload), where adding `ngf-select` and `ngf-drop` to a `<div>` makes it both a drag target and clickable.

**Comment by larvanitis** [comment] 2015-06-02 16:42
**Warning: untested code!**

Do you mean something like that?

HTML:
```html
<div ng-click="openFileChooser()" nv-file-drop uploader="uploader">
    Click me!
    <!-- the input can be anywhere -->
    <input type="file" id="hidden-file-input" nv-file-select uploader="uploader"/>
</div>
```

JS:
```js
$scope.openFileChooser = function() {
  $('#hidden-file-input).click();
};
```

CSS:
```css
#hidden-file-input { display: none; }
```


I use this mechanism using a customized button and it works.

**Comment by cosme-benito** [comment] 2015-06-02 17:50
I don't want to use jquery, though.

**Comment by larvanitis** [comment] 2015-06-02 18:17
Well that was a quick and dirty overview.

You can also do something like `document.getElementById('hidden-file-input').click()` but then you might have to handle missing element, `click()` browser incompatibilities etc. yourself.

See notes at the end of https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click

**Comment by faxdata** [comment] 2015-06-02 18:36
Thanks, @larvanitis ! Well, it's working but throws me a "$rootScope:inprog Action Already In Progress" error.

**Comment by cosme-benito** [comment] 2015-06-02 20:29
Your solution is valid and correct but I would rather not use it because that is not "the Angular way". I thought that this feature was pretty obvious to have and that I was missing something but apparently not. 

I'll try to come up with some time to make a pull request soon enough.

**Comment by maeishoj** [comment] 2015-07-07 10:06
anyone has made any progress on this? I would really like to have the clicking on drag and drop area too, and i wouldn't even mind using jquery, although I could do a simple directive if wanted it more "angular". however I don't like that it throws that "Error: [$rootScope:inprog] http://errors.angularjs.org/1.3.15/$rootScope/inprog?p0=%24apply"

I'd love to hear from you guys :)

**Comment by sacgup** [comment] 2015-09-23 14:13
Here is my workaround.
Inspired from this answer on Stackoverflow http://stackoverflow.com/a/31972856/5309195
Html

    <div ng-show="uploader.isHTML5">
        <div class="well drop-zone" nv-file-over="" over-class="drop-over" uploader="uploader" ng-click="fileChooser()">
            Drag & Drop files to upload / Click box to select files
        </div>
    </div>
    <div ng-hide="uploader.isHTML5">
        <input type="file" id="fileSelect" nv-file-select="" uploader="uploader" multiple /><br/>
    </div>

Controller

    $scope.fileChooser = function () {
        angular.element('#fileSelect').trigger('click'); //angular way
    };

**Comment by lpsBetty** [comment] 2016-02-29 16:33
I hid the input-file select and made an own simple directive for that!

````
/**
 * Dropzone directive to open file-select on click.
 * angular-file-upload cannot do that out of the box.
 */
angular.module('app').directive('lhDropzone', function ($timeout) {
  return {
    restrict: 'A',
    link: function(scope, element) {
      element.click(function() {
        $timeout(function () {
          element.find('input[type="file"]').click();
        });
      });
    }
  };
});

**Comment by lpsBetty** [comment] 2016-02-29 16:35
Duplicate of https://github.com/nervgh/angular-file-upload/issues/423 and https://github.com/nervgh/angular-file-upload/issues/553

**Comment by lpsBetty** [comment] 2016-09-06 21:41
I delete my directive again and did it just via HTML (+CSS).
It is only necessary to surround the input[type=file] with a `label` element, like this

    <label class="dropzone" nv-file-over uploader="uploader" over-class="in">
      Select File
      <input class="hidden" nv-file-select uploader="uploader" type="file" multiple />
    </label>

or set the same name for `label[for]` and `input[id]`

    <label for="avatar" class="dropzone" nv-file-over uploader="uploader" over-class="in">
      Select File
    </label>
    <input nv-file-select uploader="uploader" type="file" id="avatar" class="hidden" />

**Comment by nervgh** [comment] 2016-09-07 09:52
@lpsBetty thank you :v:

**Closed by nervgh** 2016-09-07 09:52 UTC

**Comment by NoahStevan** [comment] 2018-07-06 04:55
@lpsBetty wow that is genius.  thanks
